
###############
## AUTOSTART ##
###############
# Wiki: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Start EasyEffects i bakgrunnen (uten vindu)
exec-once = easyeffects --gapplication-service