###########
## INPUT ##
###########

# Wiki: https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs

input {
    # --- TASTATUR (Norsk oppsett) ---
    kb_layout = no
    kb_variant = 
    kb_model = pc105
    kb_options = 
    kb_rules =

    # --- MUS & GAMING (Glorious D) ---
    follow_mouse = 1
    
    # Sensitivity 0 betyr "gjør ingenting, bruk musas egne DPI".
    # Dette er best for gaming.
    sensitivity = 0 

    # 'flat' profil fjerner muse-akselerasjon (Raw Input).
    # Dette vil du ha for muskelminne i FPS-spill.
    accel_profile = flat 
    force_no_accel = true

    # --- ANNET ---
    # TKL-tastaturet ditt har ikke numpad, men denne er grei å ha på som standard
    numlock_by_default = true

    touchpad {
        natural_scroll = true
    }
}

##############
## GESTURES ##
##############