# ----------------------------------------------------- 
# NVIDIA & HARDWARE ACCELERATION SPECIFICS
# -----------------------------------------------------

# Fortell systemet at vi bruker Nvidia-drivere til alt
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Fikser Electron-apper (Discord, VS Code, Spotify) så de ikke kjører via XWayland (bedre ytelse)
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# Mange Nvidia-kort sliter med musepekeren i Hyprland (den forsvinner eller glitcher). 
# Denne linjen tvinger software-cursor som fikser problemet 99% av gangene.
# cursor {
#    no_hardware_cursors = true
#}
